#!/bin/bash
#SBATCH -n 1
#SBATCH -t 00:30:00
#SBATCH -J test
#SBATCH --gres=gpu:2
#SBATCH --constraint=gpu

module load intel/2021.1.2
module load cudatoolkit/11.4

export OMP_PROC_BIND=spread OMP_PLACES=threads OMP_NUM_THREADS=96
srun main.cuda > report 2> error
